#include "ADC.h"

volatile ADC_RAW_DATA ADC_DATA = {0, 0, 0, 0};

void ADC_Enable(void)
{
	DMA1_Ch_1_Enable(&ADC_DATA, NUMBER_OF_ADC_CHANNELS);

	RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;

		ADC1->CFGR2   =	ADC_CFGR2_CKMODE_Msk
					 |	ADC_CFGR2_OVSR_Msk
					 |	ADC_CFGR2_OVSS_3
					 |	ADC_CFGR2_OVSE;

		ADC1->CR 	 |= ADC_CR_ADVREGEN
					 |  ADC_CR_ADCAL;
		while(ADC1->CR & ADC_CR_ADCAL);

		ADC->CCR 	 |= ADC_CCR_VREFEN
					 |  ADC_CCR_TSEN;

		ADC1->CHSELR  = ADC_CHSELR_CHSEL8
					 |  ADC_CHSELR_CHSEL9
					 |	ADC_CHSELR_CHSEL17
					 |	ADC_CHSELR_CHSEL18;

		ADC1->CFGR1  |= ADC_CFGR1_AUTOFF
					 |	ADC_CFGR1_DMACFG
					 |  ADC_CFGR1_DMAEN
					 |	ADC_CFGR1_WAIT;

		ADC1->IER	 |= ADC_IER_EOSIE;

		ADC1->CR 	 |= ADC_CR_ADEN;

	NVIC_SetPriority(ADC1_COMP_IRQn, 1);
	NVIC_EnableIRQ(ADC1_COMP_IRQn);
}



void ADC_COMP_IRQHandler(void)
{

}
