#include <LEDS.h>

void LED_RED_ON (void)
{
	RCC->IOPENR  |=   RCC_IOPENR_GPIOAEN;

	GPIOA->MODER |=   GPIO_MODER_MODE15_Msk;
	GPIOA->MODER &= ~(GPIO_MODER_MODE15_1);

	GPIOA->BSRR  |=   GPIO_BSRR_BS_15;
}
void LED_RED_OFF(void)
{
	GPIOA->BSRR  |=   GPIO_BSRR_BR_15;
	GPIOA->MODER |=   GPIO_MODER_MODE15_Msk;
}

void LED_BLU_ON (void)
{
	RCC->IOPENR  |=   RCC_IOPENR_GPIOBEN;

	GPIOB->MODER |=   GPIO_MODER_MODE3_Msk;
	GPIOB->MODER &= ~(GPIO_MODER_MODE3_1);

	GPIOB->BSRR  |=   GPIO_BSRR_BS_3;
}
void LED_BLU_OFF(void)
{
	GPIOB->BSRR  |=   GPIO_BSRR_BR_3;
	GPIOB->MODER |=   GPIO_MODER_MODE3_Msk;
}

void LED_YEL_ON (void)
{
	RCC->IOPENR  |=   RCC_IOPENR_GPIOBEN;

	GPIOB->MODER |=   GPIO_MODER_MODE4_Msk;
	GPIOB->MODER &= ~(GPIO_MODER_MODE4_1);

	GPIOB->BSRR  |=   GPIO_BSRR_BS_4;
}
void LED_YEL_OFF(void)
{
	GPIOB->BSRR  |=   GPIO_BSRR_BR_4;
	GPIOB->MODER |=   GPIO_MODER_MODE4_Msk;
}

void LED_GRN_ON (void)
{
	RCC->IOPENR  |=   RCC_IOPENR_GPIOBEN;

	GPIOB->MODER |=   GPIO_MODER_MODE5_Msk;
	GPIOB->MODER &= ~(GPIO_MODER_MODE5_1);

	GPIOB->BSRR  |=   GPIO_BSRR_BS_5;
}
void LED_GRN_OFF(void)
{
	GPIOB->BSRR  |=   GPIO_BSRR_BR_5;
	GPIOB->MODER |=   GPIO_MODER_MODE5_Msk;
}
